baseURL = 'https://techvify-ai-lab.github.io/engineering-blog/'
languageCode = 'en-us'
title = 'Techvify.R&D | Engineering'
theme = 'pehtheme-hugo'

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Techvify R&D team focuses on innovative AI, generative AI, and IoT solutions, driving technological advancements and enhancing user experiences.'
	mainSections = 'posts'

[author]
	name = 'Techvify R&D'
	bio = 'The R&D team at Techvify specializes in developing cutting-edge solutions in AI, generative AI, and IoT, aiming to transform technology and enhance user experiences.'
	avatar = '/images/nasa-astronaut-unsplash.jpg'
	twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Generative AI'
		pageRef = '/tags/genai/'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'